### ISSUE TITLE
Cargo does not handle +toolchain directives.

### ISSUE THREAD

**Issue by andriyDev** [xd009642/tarpaulin#1494]
I am on Windows 10, using Rust 1.76, default toolchain set to stable-x86_64-pc-windows-msvc. I ran `cargo new --lib code-cov-example`, cd'ed into it, and ran `cargo tarpaulin` and got the following message:

```
2024-03-17T02:39:04.649653Z  INFO cargo_tarpaulin::config: Creating config
2024-03-17T02:39:04.792126Z  INFO cargo_tarpaulin: Running Tarpaulin
2024-03-17T02:39:04.792368Z  INFO cargo_tarpaulin: Building project
2024-03-17T02:39:04.792590Z  INFO cargo_tarpaulin::cargo: Cleaning project
error: no such command: `+stable-x86_64-pc-windows-msvc`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
2024-03-17T02:39:04.894216Z ERROR cargo_tarpaulin: Cargo failed to run! Error: cargo run failed
Error: "Cargo failed to run! Error: cargo run failed"
```

I'm not really sure how to debug this. I also just installed tarpaulin using `cargo install cargo-tarpaulin` like normal.

**Comment by xd009642** [comment]
This should only happen if you have the `RUSTUP_TOOLCHAIN` env var set. Which would imply that you're using rustup and `+` directives should work. 

Just wondering do you handle your rust install via rustup? And why is that environment variable set? Just trying to understand a bit more because it will have been added to fix another users issue so I don't want to just willy-nilly remove the env var check

**Comment by andriyDev** [comment]
Looking at my Windows environment variables, I don't have `RUSTUP_TOOLCHAIN` set! I am using rustup for my Rust install. I even tried using Powershell to see if it would do the trick and no luck.

**Comment by xd009642** [comment]
Sorry for the delay, I have pushed a branch with a potential fix, if you could try it out and let me know if it solves it - otherwise I'll look to different methods. The branch is `fix/broken-toolchain-directives`

**Comment by xd009642** [comment]
Doing too many PRs at once and merged this one. It's a change I likely would have merged anyway... But yeah it's in develop now!

**Comment by xd009642** [comment]
Okay this is released, I'll close the issue but if it still persists feel free to reopen

**Comment by andriyDev** [comment]
Ah dang, I lost track of this, sorry! I just upgraded to v0.29.0. Looks like the issue is still occuring :/

@xd009642 I don't think I'm able to reopen this issue.

**Comment by andriyDev** [comment]
I believe I know what the issue is: I have rustup installed to a non-default directory `E:\\Programs\RustUp`. tarpaulin includes the +toolchain directive if `.rustup` is not in the path. Instead, we should be using the `RUSTUP_HOME` environment variable if it is present.
